apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: youtoo-ingestion-metrics
  namespace: telemetry
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: youtoo-ingestion
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - telemetry
      - youtoo
