apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtoo-ingestion
  namespace: youtoo
  labels:
    app: youtoo-ingestion
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtoo-ingestion
  template:
    metadata:
      labels:
        app: youtoo-ingestion
        app.kubernetes.io/name: youtoo-ingestion
        app.kubernetes.io/version: $(VERSION)
        app.kubernetes.io/part-of: youtoo
      annotations:
        sidecar.opentelemetry.io/inject: $(OTEL_COLLECTOR)
    spec:
      containers:
        - name: youtoo-ingestion
          image: youtoo-ingestion:$(VERSION)
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8181
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_PASSWORD
            - name: YOUTOO_LOG_LEVEL
              value: $(LOG_LEVEL)
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always

