apiVersion: v1
kind: Service
metadata:
  name: youtoo-ingestion
  namespace: youtoo
  labels:
    app: youtoo-ingestion
spec:
  selector:
    app: youtoo-ingestion
  ports:
    - name: web
      port: 8181
      targetPort: 8181
      protocol: TCP
    - name: metrics
      port: 8889
      targetPort: 8889
      protocol: TCP
  type: ClusterIP
